# Generated by Django 3.2.12 on 2022-02-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='chatboard.board'),
        ),
    ]
